### ISSUE TITLE
Unable to perform "Backlog Overview"

### ISSUE THREAD

**Issue by aschnabl** [lsellens/script.module.audo-programs#3]
I can't pin down the exact date when this started, but i think it was with the update of sickrage to 4.0.18.

When i try to do a "backlog overview" i get the following error in the log:

2015-05-13 20:15:07 Thread-76 :: Failed doing webui callback: Traceback (most recent call last):
  File "/storage/.kodi/addons/script.module.audo-programs/resources/SickBeard/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/storage/.kodi/addons/script.module.audo-programs/resources/SickBeard/sickbeard/webserve.py", line 3006, in backlogOverview
    [curShow.indexerid])
  File "/storage/.kodi/addons/script.module.audo-programs/resources/SickBeard/sickbeard/db.py", line 192, in select
    sqlResults = self.action(query, args, fetchall=True)
  File "/storage/.kodi/addons/script.module.audo-programs/resources/SickBeard/sickbeard/db.py", line 170, in action
    sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/storage/.kodi/addons/script.module.audo-programs/resources/SickBeard/sickbeard/db.py", line 86, in execute
    return self._execute(query, args).fetchall()
  File "/storage/.kodi/addons/script.module.audo-programs/resources/SickBeard/sickbeard/db.py", line 235, in _unicode_text_factory
    return unicode(x, sickbeard.SYS_ENCODING)
  File "/home/stephan/projects/openelec-5.0/build.OpenELEC-RPi2.arm-5.0.6/Python-2.7.3/.install_pkg/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 703: invalid continuation byte

Everything worked fine up until a week or so ago, so the only thing i can think of is the upgrade. 

Let me know what other information you require.

**Comment by lsellens** [comment]
If you click on the general tab in settings does it just take you back to the home screen?

**Comment by aschnabl** [comment]
I got told here to "set locale to UTF-8":

https://github.com/SiCKRAGETV/sickrage-issues/issues/1592

With the general tab it takes me to the settings. Clicking Backlog Overview is the only one i found that produces this error , and takes me back to the home screen

**Comment by lsellens** [comment]
Was just curious. I had a very similar bug but it effected a lot more. Hadn't seen anyone else complain about it so I figure I just had some db corruption. Ended up nuking all the configs and db files. Set everything back up and have been running smooth ever since. I'm going to release an update probably tonight. I might have to add utf-8 to the dependencies as it seems openelec doesnt come with it. You can check installed locales in linux with the command "locale -a" but its strange I'm running just fine now without it. Seems if unicode chars were the problem I should still be having issues.

**Comment by SweBel** [comment]
I have a similar error, all my shows are lost and when trying to configure the search settings I get the following error.

2015-05-18 23:04:54 Thread-17 :: Failed doing webui callback: Traceback (most recent call last):
  File "/storage/.kodi/addons/script.module.audo-programs/resources/SickBeard/sickbeard/webserve.py", line 258, in async_call
    result = function(**kwargs)
  File "/storage/.kodi/addons/script.module.audo-programs/resources/SickBeard/sickbeard/webserve.py", line 3846, in index
    return t.respond()
  File "/storage/.kodi/userdata/addon_data/script.service.audo/sbcache/cheetah/_storage__kodi_addons_script_module_audo_programs_resources_SickBeard_gui_slick_interfaces_default_config_search_tmpl.py", line 814, in respond
    if _v is not None: write(_filter(_v, rawExpr=u'$sickbeard.TORRENT_PASSWORD')) # from line 540, col 87.
  File "/storage/.kodi/addons/script.module.audo-programs/resources/SickBeard/sickbeard/webserve.py", line 95, in filter
    logger.log(u'Unable to decode using {0}, trying utf-8. Error is: {1}'.format(sickbeard.SYS_ENCODING, ex(e)),logger.DEBUG)
  File "/storage/.kodi/addons/script.module.audo-programs/resources/SickBeard/sickbeard/exceptions.py", line 49, in ex
    e_message = e_message + " : " + fixed_arg
  File "/home/stephan/projects/openelec-5.0/build.OpenELEC-RPi2.arm-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0x97 in position 8: invalid start byte

**Comment by lsellens** [comment]
I think this might have something to do with me jumping too many versions ahead. Adding utf-8 would increase the addon size by quite a bit and I've been running fine with out it along with a lot of other users. I'm not going to be home to work on this for a while so I hate to suggest it but nuke all the configs cache and db files and set sickrage back up from scratch. Should fix this.

**Comment by SweBel** [comment]
Thanks, that did the trick!

**Comment by Luisao81** [comment]
After returning from vacation a few days ago, I started to get the same error. It must've broken sometime in the last 3 weeks. Whenever I click Search Settings it takes me to the Home screen. It's not   snatching either. Is there a list of steps somewhere that I can follow to only delete Sickrage's files to set it up from scratch ?
